stages:
    - build

before_script:
    - npm install --registry=http://registry.npm.souche-inc.com
    - ./node_modules/.bin/lerna bootstrap --npm-client npm --registry=http://registry.npm.souche-inc.com

build:
    stage: build
    only:
        - master
    script:
        - npm run lint
        # - npm run test  no test service on gitlab anymore
        - npm run build
