/* Automatic generated by './build/bin/build-entry.js' */
import AccordionTransition from './transitions/accordion-transition';

import LoadingPlugin from './plugins/loading';
import ToastPlugin from './plugins/toast';
import ModalPlugin from './plugins/modal';
import ConfigPlugin from './plugins/config';
import TransferDom from './directives/transfer-dom';

import Button from './components/button';
import ButtonGroup from './components/button-group';
import WingBank from './components/wing-bank';
import WhiteSpace from './components/white-space';
import Icon from './components/icon';
import List from './components/list';
import ListItem from './components/list-item';
import Radio from './components/radio';
import NoticeBar from './components/notice-bar';
import Loading from './components/loading';
import Toast from './components/toast';
import Dialog from './components/dialog';
import ActionSheet from './components/action-sheet';
import Modal from './components/modal';
import Badge from './components/badge';
import Accordion from './components/accordion';
import AccordionPanel from './components/accordion-panel';
import Tabs from './components/tabs';
import TabItem from './components/tab-item';
import Popup from './components/popup';
import Flexbox from './components/flexbox';
import FlexboxItem from './components/flexbox-item';
import TabBar from './components/tab-bar';
import TabBarItem from './components/tab-bar-item';
import Tips from './components/tips';
import TipsItem from './components/tips-item';
import Picker from './components/picker';
import Checkbox from './components/checkbox';
import CheckboxGroup from './components/checkbox-group';
import DatePicker from './components/date-picker';
import Tag from './components/tag';
import TagGroup from './components/tag-group';
import Textarea from './components/textarea';
import Input from './components/input';
import SegmentedControl from './components/segmented-control';
import SegmentedControlItem from './components/segmented-control-item';
import NavBar from './components/nav-bar';
import SearchBar from './components/search-bar';
import IndexList from './components/index-list';
import Result from './components/result';
import Filter from './components/filter';
import FilterItem from './components/filter-item';
import Flow from './components/flow';
import FlowItem from './components/flow-item';
import Sticky from './components/sticky';
import Switch from './components/switch';
import AnimateNumber from './components/animate-number';
import Range from './components/range';
import Progress from './components/progress';
import TimePicker from './components/time-picker';
import DateTimePicker from './components/date-time-picker';
import Select from './components/select';
import Rate from './components/rate';
import Keyboard from './components/keyboard';

const components = [
    Button,
    ButtonGroup,
    WingBank,
    WhiteSpace,
    Icon,
    List,
    ListItem,
    Radio,
    NoticeBar,
    Loading,
    Toast,
    Dialog,
    ActionSheet,
    Modal,
    Badge,
    Accordion,
    AccordionPanel,
    Tabs,
    TabItem,
    Popup,
    Flexbox,
    FlexboxItem,
    TabBar,
    TabBarItem,
    Tips,
    TipsItem,
    Picker,
    Checkbox,
    CheckboxGroup,
    DatePicker,
    Tag,
    TagGroup,
    Textarea,
    Input,
    SegmentedControl,
    SegmentedControlItem,
    NavBar,
    SearchBar,
    IndexList,
    Result,
    Filter,
    FilterItem,
    Flow,
    FlowItem,
    Sticky,
    Switch,
    AnimateNumber,
    Range,
    Progress,
    TimePicker,
    DateTimePicker,
    Select,
    Rate,
    Keyboard,
    AccordionTransition
];

const install = function(Vue) {
    /* istanbul ignore if */
    if (install.installed) return;

    components.map((component) => {
        Vue.component(component.name, component);
    });

    Vue.use(LoadingPlugin);
    Vue.use(ToastPlugin);
    Vue.use(ModalPlugin);
};

// Vue 是全局变量的时候自动安装这些插件
/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}

module.exports = {
    version: '4.5.12',
    install,
    AccordionTransition,
    LoadingPlugin,
    ToastPlugin,
    ModalPlugin,
    ConfigPlugin,
    TransferDom,
    Button,
    ButtonGroup,
    WingBank,
    WhiteSpace,
    Icon,
    List,
    ListItem,
    Radio,
    NoticeBar,
    Loading,
    Toast,
    Dialog,
    ActionSheet,
    Modal,
    Badge,
    Accordion,
    AccordionPanel,
    Tabs,
    TabItem,
    Popup,
    Flexbox,
    FlexboxItem,
    TabBar,
    TabBarItem,
    Tips,
    TipsItem,
    Picker,
    Checkbox,
    CheckboxGroup,
    DatePicker,
    Tag,
    TagGroup,
    Textarea,
    Input,
    SegmentedControl,
    SegmentedControlItem,
    NavBar,
    SearchBar,
    IndexList,
    Result,
    Filter,
    FilterItem,
    Flow,
    FlowItem,
    Sticky,
    Switch,
    AnimateNumber,
    Range,
    Progress,
    TimePicker,
    DateTimePicker,
    Select,
    Rate,
    Keyboard
};
